// slash-ui.js — explicit slash-bass control plus recording/playback persistence.
// The main app keeps bass as a global performance setting; this extension records
// the chosen bass on each chord event and re-applies it only while that event is
// being scheduled, so a recorded C/E remains C/E even after the global setting changes.

import { saveSettings } from './settings.js';

const body = document.getElementById('drawerBody');

const CUSTOM_NOTES = [
  ['C', 0], ['C♯/D♭', 1], ['D', 2], ['D♯/E♭', 3],
  ['E', 4], ['F', 5], ['F♯/G♭', 6], ['G', 7],
  ['G♯/A♭', 8], ['A', 9], ['A♯/B♭', 10], ['B', 11],
];

function state() {
  return window.chordPad?.state || null;
}

function recorder() {
  return window.chordPad?.recorder || null;
}

function labelFor(value) {
  if (value === 'off') return 'Off';
  if (value === 'root') return 'Root';
  if (value === 'third') return '3rd (slash)';
  if (value === 'fifth') return '5th (slash)';
  if (value?.startsWith('pc:')) {
    const pc = Number(value.slice(3));
    const found = CUSTOM_NOTES.find(([, n]) => n === pc);
    return found ? `/${found[0]}` : 'Custom';
  }
  return 'Off';
}

function makeOption(select, value, text) {
  const opt = document.createElement('option');
  opt.value = value;
  opt.textContent = text;
  select.append(opt);
}

// app.js currently reads state.bass synchronously inside startChord(). During recorded
// playback it first reads event.playback and then immediately starts that chord. A
// temporary accessor lets us present the recorded bass for exactly that synchronous
// scheduling pass, then restore the user's current live setting in a microtask.
let restoreQueued = false;
let restoreBass = null;

function applyRecordedBass(bass) {
  const s = state();
  if (!s) return;
  if (!restoreQueued) {
    restoreQueued = true;
    restoreBass = s.bass;
    queueMicrotask(() => {
      const current = state();
      if (current) current.bass = restoreBass;
      restoreBass = null;
      restoreQueued = false;
    });
  }
  s.bass = bass || 'off';
}

function decorateEvent(event) {
  if (!event || event.__slashDecorated) return;
  let playbackValue = event.playback ?? null;
  Object.defineProperty(event, 'playback', {
    configurable: true,
    enumerable: true,
    get() {
      applyRecordedBass(event.bass || 'off');
      return playbackValue;
    },
    set(value) { playbackValue = value; },
  });
  Object.defineProperty(event, '__slashDecorated', {
    configurable: true,
    enumerable: false,
    value: true,
  });
}

function decorateAllEvents() {
  const r = recorder();
  if (!r) return;
  for (const event of r.events) decorateEvent(event);
}

function installRecordingHooks() {
  const r = recorder();
  const s = state();
  if (!r || !s || r.__slashHooksInstalled) return;

  const originalNoteOn = r.noteOn.bind(r);
  r.noteOn = (padId, chord, playback, now) => {
    originalNoteOn(padId, chord, playback, now, state()?.bass || 'off');
    decorateEvent(r.events[r.events.length - 1]);
  };

  const originalLoadProgression = r.loadProgression.bind(r);
  r.loadProgression = (ids, chords, measureDur) => {
    originalLoadProgression(ids, chords, measureDur, state()?.bass || 'off');
    decorateAllEvents();
  };

  const originalLoad = r.load.bind(r);
  r.load = () => {
    originalLoad();
    decorateAllEvents();
  };

  Object.defineProperty(r, '__slashHooksInstalled', {
    enumerable: false,
    value: true,
  });
  decorateAllEvents();
}

function install() {
  const s = state();
  installRecordingHooks();
  if (!body || !s || body.querySelector('[data-slash-bass]')) return;

  // Replace the older Root/Auto/Off field generated by app.js.
  const fields = [...body.querySelectorAll('.field')];
  const oldBass = fields.find((field) => field.querySelector('.field-label span')?.textContent === 'Bass note');

  const wrap = document.createElement('div');
  wrap.className = 'field';
  wrap.dataset.slashBass = 'true';

  const label = document.createElement('div');
  label.className = 'field-label';
  const title = document.createElement('span');
  title.textContent = 'Bass / Slash chord';
  const value = document.createElement('span');
  value.className = 'value';
  value.textContent = labelFor(s.bass);
  label.append(title, value);

  const select = document.createElement('select');
  makeOption(select, 'off', 'Off — chord only');
  makeOption(select, 'root', 'Root bass');
  makeOption(select, 'third', '3rd — e.g. C/E');
  makeOption(select, 'fifth', '5th — e.g. C/G');
  for (const [name, pc] of CUSTOM_NOTES) makeOption(select, `pc:${pc}`, `Custom /${name}`);
  select.value = s.bass || 'off';

  const help = document.createElement('p');
  help.className = 'note';
  help.textContent = 'The upper chord stays unchanged. 3rd and 5th create normal inversions; Custom can create chords such as C/D. Recordings remember the selected slash bass for each chord.';

  select.addEventListener('change', () => {
    const current = state();
    if (!current) return;
    current.bass = select.value;
    value.textContent = labelFor(current.bass);
    saveSettings(current);
  });

  wrap.append(label, select, help);
  if (oldBass) oldBass.replaceWith(wrap);
  else body.append(wrap);
}

const observer = new MutationObserver(() => queueMicrotask(install));
observer.observe(body, { childList: true });
install();
