// slash-ui.js — small UI extension for explicit slash-bass control.
// The audio engine already treats bass independently from the upper chord.
// This module replaces the older Root/Auto/Off field with a more musical selector.

import { saveSettings } from './settings.js';

const body = document.getElementById('drawerBody');

const CUSTOM_NOTES = [
  ['C', 0], ['C♯/D♭', 1], ['D', 2], ['D♯/E♭', 3],
  ['E', 4], ['F', 5], ['F♯/G♭', 6], ['G', 7],
  ['G♯/A♭', 8], ['A', 9], ['A♯/B♭', 10], ['B', 11],
];

function state() {
  return window.chordPad?.state || null;
}

function labelFor(value) {
  if (value === 'off') return 'Off';
  if (value === 'root') return 'Root';
  if (value === 'third') return '3rd (slash)';
  if (value === 'fifth') return '5th (slash)';
  if (value?.startsWith('pc:')) {
    const pc = Number(value.slice(3));
    const found = CUSTOM_NOTES.find(([, n]) => n === pc);
    return found ? `/${found[0]}` : 'Custom';
  }
  return 'Off';
}

function makeOption(select, value, text) {
  const opt = document.createElement('option');
  opt.value = value;
  opt.textContent = text;
  select.append(opt);
}

function install() {
  const s = state();
  if (!body || !s || body.querySelector('[data-slash-bass]')) return;

  // Remove the original Bass note segmented control generated by app.js.
  const fields = [...body.querySelectorAll('.field')];
  const oldBass = fields.find((field) => field.querySelector('.field-label span')?.textContent === 'Bass note');

  const wrap = document.createElement('div');
  wrap.className = 'field';
  wrap.dataset.slashBass = 'true';

  const label = document.createElement('div');
  label.className = 'field-label';
  const title = document.createElement('span');
  title.textContent = 'Bass / Slash chord';
  const value = document.createElement('span');
  value.className = 'value';
  value.textContent = labelFor(s.bass);
  label.append(title, value);

  const select = document.createElement('select');
  makeOption(select, 'off', 'Off — chord only');
  makeOption(select, 'root', 'Root bass');
  makeOption(select, 'third', '3rd — e.g. C/E');
  makeOption(select, 'fifth', '5th — e.g. C/G');
  for (const [name, pc] of CUSTOM_NOTES) makeOption(select, `pc:${pc}`, `Custom /${name}`);
  select.value = s.bass || 'off';

  const help = document.createElement('p');
  help.className = 'note';
  help.textContent = 'The upper chord stays unchanged. 3rd and 5th create normal inversions; Custom can create chords such as C/D.';

  select.addEventListener('change', () => {
    const current = state();
    if (!current) return;
    current.bass = select.value;
    value.textContent = labelFor(current.bass);
    saveSettings(current);
  });

  wrap.append(label, select, help);
  if (oldBass) oldBass.replaceWith(wrap);
  else body.append(wrap);
}

const observer = new MutationObserver(() => queueMicrotask(install));
observer.observe(body, { childList: true });
install();
